train: []
inference:
    #4-24
  - _target_: src.metrics.MOSNet
    name: "MOS_4_24"
    sr: 24000
  - _target_: src.metrics.ScaleInvariantSignalToDistortionRatio
    name: "SISDR_4_24"
  - _target_: src.metrics.SignalToNoiseRatio
    name: "SNR_4_24"
  - _target_: src.metrics.LSD
    name: "LSD_4_24"
  - _target_: src.metrics.LSD_LF
    name: "LSD_LF_4_24"
  - _target_: src.metrics.LSD_HF
    name: "LSD_HF_4_24"
  - _target_: src.metrics.STOI
    name: "STOI_4_24"
    sr: 24000
  - _target_: src.metrics.PESQ
    name: "PESQ_4_24"
    sr: 24000
  - _target_: src.metrics.CSIG
    name: "CSIG_4_24"
  - _target_: src.metrics.CBAK
    name: "CBAK_4_24"
  - _target_: src.metrics.COVL
    name: "COVL_4_24"
