_target_: src.model.HiFiPlusPlusGAN  
generator_config:
  upsample_block_rates: [2]
  upsample_block_kernel_sizes: [4]

  residual_channels: 64
  bsft_channels: 64
  nwstack1_blocks: 1
  nwstack2_blocks: 1

  use_waveunet: True
  waveunet_block_widths: [10, 20, 40, 80]
  waveunet_block_depth: 4

  norm_type: "weight"
  use_skip_connect: True
  waveunet_input: "both"
  waveunet_channels: 8

  convnext_dim: 513
  num_layers_convnext_real: 8
  num_layers_convnext_imag: 1
  intermediate_dim_convnext: 1536

mpd_config: 
  periods: [2, 3, 5, 7, 11]
  kernel_size: 5
  stride: 3
  channels: [1, 32, 128, 512, 1024]

msd_config: 
  num_blocks: 3
  kernel_sizes: [15, 41, 41, 41, 41, 41, 5]
  strides: [1, 2, 2, 4, 4, 1, 1]
  groups: [1, 4, 16, 16, 16, 16, 1]
  channels: [1, 128, 128, 256, 512, 1024, 1024, 1024]
