defaults:
  - model: model
  - metrics: test_metrics_4_16
  - datasets: test_dataset
  - dataloader: test_loader
  - _self_
inferencer:
  device_tensors: ["wav_lr", "wav_hr", "melspec_lr", "melspec_hr"]
  device: auto
  save_path: "inference_dir"
  seed: 1
  from_pretrained: "/Users/polinakadeyshvili/AMI/4_course/diplom/varying_sr/saved_dir/train_3_regimes_new_metrics/model_best.pth"