_target_: src.logger.TensorboardFramework
project_name: "bweHiFi"
workspace: null
run_name: "WoSpec_V2(cont)"
log_dir: "./tensb/WoSpec_V2(cont)"
loss_names: ["gen_loss", "disc_loss", "mpd_gen_loss", "msd_gen_loss", "mel_spec_loss", "mpd_feats_gen_loss", "msd_feats_gen_loss", "mpd_disc_loss", "msd_disc_loss"]
log_checkpoints: False # set to True if you want to log save_dir with checkpoints to W&B
id_length: 32 # length of the run_id